# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dholiday <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/05 11:46:01 by dholiday          #+#    #+#              #
#    Updated: 2019/04/19 15:05:55 by mkami            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

HDR = libft.h

FLAGS = -Wall -Wextra -Werror

SRC = ft_bzero.c \
	  ft_isascii.c \
	  ft_isalpha.c \
	  ft_isalnum.c \
	  ft_isdigit.c \
	  ft_isprint.c \
	  ft_memchr.c \
	  ft_memmove.c \
	  ft_memcmp.c \
	  ft_memset.c \
	  ft_memcpy.c \
	  ft_memccpy.c \
	  ft_strchr.c \
	  ft_tolower.c \
	  ft_strrchr.c \
	  ft_toupper.c \
	  ft_strstr.c \
	  ft_strnstr.c \
	  ft_atoi.c \
	  ft_strcpy.c \
	  ft_strcat.c \
	  ft_strdup.c \
	  ft_strlen.c \
	  ft_strcmp.c \
	  ft_strncmp.c \
	  ft_strncat.c \
	  ft_strlcat.c \
	  ft_strncpy.c \
	  ft_putchar.c \
	  ft_putnbr.c \
	  ft_putstr.c \
	  ft_striter.c \
	  ft_striteri.c \
	  ft_strmap.c \
	  ft_strmapi.c \
	  ft_strequ.c \
	  ft_strnequ.c \
	  ft_memalloc.c \
	  ft_memdel.c \
	  ft_strnew.c \
	  ft_strdel.c \
	  ft_strclr.c \
	  ft_strsub.c \
	  ft_strjoin.c \
	  ft_putendl.c \
	  ft_strtrim.c \
	  ft_strsplit.c \
	  ft_itoa.c \
	  ft_putchar_fd.c \
	  ft_putstr_fd.c \
	  ft_putendl_fd.c \
	  ft_putnbr_fd.c \
	  ft_lstnew.c \
	  ft_lstdelone.c \
	  ft_lstdel.c \
	  ft_lstadd.c \
	  ft_lstiter.c \
	  ft_lstmap.c \
	  words.c \
	  wordlen.c \
	  refresh.c \
	  charlen.c \
	  ft_list_push_back.c \
	  ft_swap.c \
	  get_next_line.c
all: $(NAME)

$(NAME):
	gcc $(FLAGS) -c -I $(HDR) $(SRC)
	ar rc $(NAME) $(SRC:.c=.o)

clean:
	/bin/rm -f $(SRC:.c=.o)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
